services:
  - type: web
    name: venom-service
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reservas_DB
          property: connectionString
      - key: PORT
        value: 3000
    autoDeploy: true
    rootDir: venom-service