import os
import json

ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ADMIN_PASSWORD = os.environ["ADMIN_PASSWORD"]
ADMIN_USER = os.environ["ADMIN_USER"]
DATABASE_URL = os.environ["DATABASE_URL"]
GOOGLE_CALENDAR_ID = os.environ["GOOGLE_CALENDAR_ID"]
GOOGLE_CREDENTIALS_JSON = os.environ["GOOGLE_CREDENTIALS_JSON"]
PHONE_NUMBER_ID = os.environ["PHONE_NUMBER_ID"]
SECRET_KEY = os.environ["SECRET_KEY"]
VERIFY_TOKEN = os.environ["VERIFY_TOKEN"]

GOOGLE_CREDENTIALS = json.loads(GOOGLE_CREDENTIALS_JSON)