"""migracion para no borrar todo cada vez q subo algo

Revision ID: 1199f224ce24
Revises: 
Create Date: 2025-06-10 10:51:09.445511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1199f224ce24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tenant_telefono_key'), type_='unique')

    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_column('calendar_id')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('tenant_telefono_key'), ['telefono'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
