"""add meta whatsapp credentials to tenantconfig

Revision ID: cfcadd36d6a8
Revises: 1199f224ce24
Create Date: 2025-06-10 11:07:36.140249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcadd36d6a8'
down_revision = '1199f224ce24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verify_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_column('access_token')
        batch_op.drop_column('verify_token')
        batch_op.drop_column('phone_number_id')

    # ### end Alembic commands ###
